### ISSUE TITLE
Support for custom role location

### ISSUE THREAD

**Issue by zekker6** [robertdebock/galaxy-action#1]
It would be great to have support of configuring path to the role via action.
In my use case it is planned to have mono repo for different roles and it would be awesome to use this action to handle this.

P.S. if it is already possible to use it like this could you please point me to the right configuration parameter?

**Comment by robertdebock** [comment]
This was not possible, but version 1.1.0 allows you to set `path`. Let me know if this works for you or if you require further changes.

Thanks for the idea, much appreciated!
