### ISSUE TITLE
only release for master branch?

### ISSUE THREAD

**Issue by stefangweichinger** [robertdebock/galaxy-action#2]
Is there a way to only publish after successful molecule tests on master branch?

Right now it also publishes test runs from my test branches ... not as intended.

The goal: the same workflow should run the molecule tests for test- and master-branches, but the release step should only happen in master branch.

**Comment by robertdebock** [comment]
I think you can tell GitHub Actions to run on specific branches:

```yaml
on:
  push:
    branches:
      - master
```

**Comment by stefangweichinger** [comment]
It has to be more specific, only that one release step should be skipped or not.
I think I found it:

https://github.com/stefangweichinger/ansible-rclone/commit/96d4551dfef179ec1c7f907c9145c234bb633422

thanks

**Comment by weakcamel** [comment]
There's a catch: you can trigger a release from a feature branch, but if my observations and conclusions are correct - this will still publish metadata (possibly code too) from the `master` branch only.

See https://github.com/speechmatics/ansible-role-hostname/pull/2#issuecomment-872941476

@robertdebock would you say they're correct or am I doing something silly?
