### ISSUE TITLE
Issue with version 1.1.0 & 1.2.0

### ISSUE THREAD

**Issue by stiliajohny** [robertdebock/galaxy-action#5]
Hi 

After tagging your repo to version 1.2.0, version 1.1.1 is requiring a branch name, 
when I give `git_branch` it is not accepting it unless I update on 1.2.0

![image](https://user-images.githubusercontent.com/17669235/164946115-81abd695-e307-4365-a3bf-39a3d7b74133.png)

**Comment by tersmitten** [comment]
I have the same issue

**Comment by robertdebock** [comment]
I see that [the docker container](https://github.com/robertdebock/docker-github-action-galaxy) is not picking up the environment variable `git_branch`.

Let me fix that.

**Comment by robertdebock** [comment]
Should be fixed now, let me know if you still experience issue please.
