### ISSUE TITLE
Can't publish role if inside sub-dir.

### ISSUE THREAD

**Issue by lotyp** [robertdebock/galaxy-action#7]
Created template and I'm using your action for publishing. Everything works if in root path.

https://github.com/wayofdev/ansible-role-tpl/tree/feat-experimental

Saw, that docker does not get path env variable and added it, but still I get same error.

https://github.com/robertdebock/galaxy-action/pull/6

Looks like a bug, and needs more debugging :(

**Comment by lotyp** [comment]
Ok, did some debugging, and it is limitation of ansible-galaxy. But there still is bug, when path env var isn't passed. See PR.

**Comment by robertdebock** [comment]
Thanks for the PR, merged. I'll do the work to release this in a bit.
