### ISSUE TITLE
cannot publish a collection to galaxy

### ISSUE THREAD

**Issue by pescobar** [robertdebock/galaxy-action#9]
I was using this action to publish a collection to galaxy (https://github.com/scicore-unibas-ch/ansible-modules-guacamole/blob/68f7f35cf36d32872e2b9fb4b1e5e0a8f111ca4c/.github/workflows/main.yml#L57-L67) and it was working fine but now I am getting this error:

`Task "883203" failed: Role not found. GitHub repository import supports only a single top-level role. To import multiple contents, please follow the collection import workflow`

I guess something changed in galaxy?

**Comment by robertdebock** [comment]
I'm not sure, looking at the error, your role is is not structured as Galaxy expects is.

Anyway, closing the issue.
